### ISSUE TITLE
How are you folks using complex types in your project variables?

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/terraform-tfe-cloud-infrastructure-automation#4]
## Describe the Bug

Using complex types in project `vars` (lists or maps) seems to break the variables module for [project.variables](https://github.com/cloudposse/terraform-tfe-cloud-infrastructure-automation/blob/master/modules/project/main.tf#L20). 

Using complex types breaks in a couple ways: 

1. Due to type constraints around the `map` type, `project_values` will error with "map elements must have the same type" if project values includes any non-primitive types. 
   - The doc to read to understand this issue is https://www.terraform.io/docs/configuration/types.html#conversion-of-complex-types
   - I fixed the above here: https://github.com/cloudposse/terraform-tfe-cloud-infrastructure-automation/commit/7a2d32b8e91f963a71b8835191cac4e0e661b3eb on my own currently long running branch, which gets me past this issue. 
2. Once past that issue however, the `jsonencode` in [modules/variables/main.tf](https://github.com/cloudposse/terraform-tfe-cloud-infrastructure-automation/blob/master/modules/variables/main.tf#L9) causes another runtime error (see screenshot below): 

> The true and false result expressions must have consistent types. The given
> expressions are string and tuple, respectively.

It seems like this would be something that ya'll would have run into or maybe I'm going about it wrong. Figured I'd open up an issue to discuss. 

## Expected Behavior

I expect a project's `vars` to support maps and lists. 

## Steps to Reproduce
1. Updates a project's vars section in yaml to have the following in your config project: 
```
instance_types:
  - "m5.xlarge"
```
2. Push the change
3. See TFC error with the issue outlined above in \#1. 
4. If you want to go further, update to use the `gowiem-updates` branch, push the change, and see the issue above in \#2. 

## Screenshots
![image](https://user-images.githubusercontent.com/1392040/102936715-e3d98080-4465-11eb-9c3f-3068646b9f45.png)

Configuration which reproduces on the `gowiem-updates` branch: 

![image](https://user-images.githubusercontent.com/1392040/102940255-2488c800-446d-11eb-8758-eebab7ab698d.png)

## Additional Context

Just wondering if this is a bug or if this is some issue on my end that I'm not understanding. Happy to work through a fix if this is a bug and we can define a path forward.

**Comment by Gowiem** [comment]
cc @osterman @htplbc, for when ya'll get the chance, let me know what your thoughts on the above are.

**Comment by osterman** [comment]
Complex types should be supported. As you can see from the hack in this line, we encode it to json and then butcher it to HCL.

![image](https://user-images.githubusercontent.com/52489/102967032-f2e02300-44a5-11eb-8e98-7ed4031600ca.png)

Can you try removing the ternary and just always setting it to the JSON encoded value to see if it works?

I believe @danjbh is using a similar pattern in our space lift module: https://github.com/cloudposse/terraform-spacelift-cloud-infrastructure-automation

**Comment by osterman** [comment]
(also, maybe some change in behavior from 0.13 and 0.14)

**Comment by Gowiem** [comment]
@osterman figured it out after a tiny bit of finagling. This does the trick: https://github.com/cloudposse/terraform-tfe-cloud-infrastructure-automation/compare/gowiem-updates#diff-2e132b866c88cc3d2c71eaa0d80a9bc444a4f1bce46f4ed6656f166e88550815

Using just the jsonencoded value means that environment vars end up jsonencoded which breaks them as they are quoted like the below screenshot (results in runtime error): 

![image](https://user-images.githubusercontent.com/1392040/103251515-2c95ab80-4936-11eb-9154-ae93a8a35912.png)

So, the hcl flag is needed, but we just need to avoid the ternary operator as the type conversion / explicitness required by HCL is a bit janky. Instead of using the ternary operator, I came up with the `merge` / `if` pattern used in the above diff which removes the need to potentially have type differences in a ternary like I was running into. It's a bit funky, but hopefully the comments convey enough of the root issue. 

@htplbc if you had another way of solving this for ya'lls usage, I would love to hear it! Otherwise, PR will be up in a day or two and we can chat through more there.

Thanks folks!

**Comment by osterman** [comment]
Awesome @Gowiem ! Looks like you are on the right track
